services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_URL: ${DB_URL}
        BOOK_FILEPATH: ${BOOK_FILEPATH}
        SOLUTIONS_FILEPATH: ${SOLUTIONS_FILEPATH}
    container_name: telegram-bot
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - docker/.env
    command: python app.py
