services:
  app:
    build: .
    container_name: parse_probability_app
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - DB_URL=${DB_URL}
      - BOOK_FILEPATH=${BOOK_FILEPATH}
      - SOLUTIONS_FILEPATH=${SOLUTIONS_FILEPATH}
      - BOT_TOKEN=${BOT_TOKEN}
    command: python app.py
