services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-bot
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - docker/.env
    command: python app.py
