from app.database.models.base import Base
from app.database.models.exercises import Exercise
from app.database.models.solutions import Solution
from app.database.models.paragraphs import Paragraph
from app.database.models.sections import Section
from app.database.models.users import User
from app.database.models.solved_exercises import SolvedExercise
from app.database.models.selected_sections import SelectedSection
from app.database.models.selected_paragraphs import SelectedParagraph
from app.database.models.tables import Table
